import CoreFoundation
import Foundation

enum AppLanguage: String, CaseIterable {
    case system
    case simplifiedChinese
    case traditionalChinese
    case english
    case japanese
    case korean

    var displayName: String {
        switch self {
        case .system: L.text("跟随系统")
        case .simplifiedChinese: "简体中文"
        case .traditionalChinese: "繁體中文"
        case .english: "English"
        case .japanese: "日本語"
        case .korean: "한국어"
        }
    }
}

enum AppLanguagePreferences {
    private static let languageKey = "appLanguage"

    static func selectedLanguage(defaults: UserDefaults = .standard) -> AppLanguage {
        guard let rawValue = defaults.string(forKey: languageKey),
              let language = AppLanguage(rawValue: rawValue) else {
            return .system
        }
        return language
    }

    static func setSelectedLanguage(_ language: AppLanguage, defaults: UserDefaults = .standard) {
        defaults.set(language.rawValue, forKey: languageKey)
    }
}

enum L {
    private enum Language {
        case simplifiedChinese
        case traditionalChinese
        case japanese
        case korean
        case english
    }

    private static let english: [String: String] = [
        "区域截图": "Capture Region",
        "长截图": "Scrolling Capture",
        "区域录屏": "Record Region",
        "全屏录屏": "Record Full Screen",
        "录屏": "Record",
        "全屏截图": "Full Screen Capture",
        "延时截图…": "Delayed Capture...",
        "从剪贴板贴图": "Pin from Clipboard",
        "贴图库…": "Pin Library...",
        "隐藏全部贴图": "Hide All Pins",
        "显示全部贴图": "Show All Pins",
        "贴图": "Pins",
        "退出 Brushot": "Quit Brushot",
        "编辑": "Edit",
        "撤销": "Undo",
        "重做": "Redo",
        "剪切": "Cut",
        "复制": "Copy",
        "粘贴": "Paste",
        "全选": "Select All",
        "Brushot 截图": "Brushot Screenshot",
        "偏好设置…": "Preferences...",
        "水印设置…": "Watermark Settings...",
        "问题反馈…": "Feedback...",
        "问题反馈": "Feedback",
        "QQ交流群：1063488835\n联系邮箱：brushot@163.com": "QQ group: 1063488835\nEmail: brushot@163.com",
        "贴图失败": "Pin Failed",
        "快捷键不可用": "Shortcut Unavailable",
        "该快捷键可能已被其他应用占用，请换一个组合。": "This shortcut may already be used by another app. Choose a different combination.",
        "快捷键冲突": "Shortcut Conflict",
        "该快捷键已用于“%@”，请换一个组合。": "This shortcut is already used by \"%@\". Choose a different combination.",
        "偏好设置": "Preferences",
        "开机自动启动": "Launch at Login",
        "启用 OCR 英译中": "Enable OCR English to Chinese",
        "启用 OCR 英译中（需要 macOS 15 或更高版本）": "Enable OCR English to Chinese (requires macOS 15 or later)",
        "播放操作完成提示音": "Play completion sound",
        "通用": "General",
        "语言": "Language",
        "应用语言": "App Language",
        "跟随系统": "Follow System",
        "重新启动 Brushot 后生效": "Takes effect after restarting Brushot",
        "选择…": "Choose...",
        "保存位置": "Save Location",
        "存储格式": "Format",
        "添加阴影": "Add Shadow",
        "阴影大小:": "Shadow Size:",
        "颜色:": "Color:",
        "增加圆角": "Round Corners",
        "默认圆角大小:": "Default Corner Radius:",
        "图片": "Image",
        "启用选区放大镜与取色": "Enable selection magnifier and color picker",
        "默认关闭。开启后会实时读取鼠标附近屏幕，可能触发 macOS 屏幕捕捉提示。": "Off by default. When enabled, Brushot reads the screen near the pointer and may trigger macOS screen capture prompts.",
        "截图": "Screenshot",
        "倒计时时长": "Countdown Duration",
        "播放倒计时提示音": "Play countdown sound",
        "延时截图": "Delayed Capture",
        "快捷键": "Shortcuts",
        "快捷键必须包含 ⌘、⌃ 或 ⌥；重复或已被系统占用的组合不会保存。": "Shortcuts must include Command, Control, or Option. Duplicates and system-reserved combinations are not saved.",
        "截图与录制": "Screenshots and Recording",
        "输入新快捷键…": "Enter new shortcut...",
        "水印设置": "Watermark Settings",
        "启用截图水印": "Enable screenshot watermark",
        "应用到录制视频/GIF": "Apply to recordings/GIFs",
        "水印说明": "Watermark info",
        "设置水印": "Set Up Watermark",
        "应用到本次截图": "Apply to This Screenshot",
        "应用并开启录制水印": "Apply and Enable Recording Watermark",
        "添加文字或 Logo，应用到当前截图": "Add text or a logo for this screenshot",
        "添加文字或 Logo，用于导出的视频或 GIF": "Add text or a logo to exported videos or GIFs",
        "请添加文字或 Logo；位置、透明度和大小沿用水印设置": "Add text or a logo. Position, opacity, and size use Watermark Settings.",
        "文字和 Logo 至少填写一项": "Enter watermark text or choose a logo.",
        "位置、透明度和大小沿用水印设置": "Position, opacity, and size use your Watermark Settings.",
        "例如：Brushot {datetime}": "Example: Brushot {datetime}",
        "可使用 {date}、{time}、{datetime}": "You can use {date}, {time}, and {datetime}",
        "文字": "Text",
        "移除": "Remove",
        "支持 PNG/JPG/HEIC，小于 3MB；": "Supports PNG/JPG/HEIC under 3 MB.",
        "重复方式": "Repeat",
        "位置": "Position",
        "透明度": "Opacity",
        "大小": "Size",
        "边距": "Margin",
        "文字颜色": "Text Color",
        "水印": "Watermark",
        "水印图片无效": "Invalid Watermark Image",
        "未选择": "None selected",
        "已选择": "Selected",
        "使用当前文字和 Logo 样式应用截图水印": "Apply the current text and logo style to screenshots",
        "导出时添加水印，不会在录制过程中显示": "Adds the watermark during export; it is not shown while recording",
        "截图水印说明": "Screenshot watermark info",
        "录制水印说明": "Recording watermark info",
        "请先填写水印文字或选择 Logo": "Enter watermark text or choose a logo first",
        "取消": "Cancel",
        "开始倒计时": "Start Countdown",
        "%d 秒后截图": "Capture in %d seconds",
        "%d 秒": "%d seconds",
        "选择": "Select",
        "矩形": "Rectangle",
        "圆形": "Ellipse",
        "直线": "Line",
        "箭头": "Arrow",
        "画笔": "Pen",
        "步骤": "Step",
        "马赛克": "Mosaic",
        "高亮": "Highlight",
        "添加标注": "Add Annotation",
        "删除标注": "Delete Annotation",
        "修改标注": "Modify Annotation",
        "移动标注": "Move Annotation",
        "移动步骤文字": "Move Step Text",
        "缩放标注": "Resize Annotation",
        "编辑文字": "Edit Text",
        "编辑步骤文字": "Edit Step Text",
        "粗细": "Stroke",
        "字号": "Font Size",
        "笔宽": "Brush",
        "取消 (Esc)": "Cancel (Esc)",
        "识别文字": "Recognize Text",
        "复制 (⌘C)": "Copy (⌘C)",
        "保存 (⌘S)": "Save (⌘S)",
        "正在冻结截图…": "Freezing screenshot...",
        "关闭本次截图水印": "Disable watermark for this screenshot",
        "开启本次截图水印": "Enable watermark for this screenshot",
        "完成": "Done",
        "%@，快捷键 %@": "%@, shortcut %@",
        "选择标注颜色": "Choose annotation color",
        "实线": "Solid",
        "虚线": "Dashed",
        "点线": "Dotted",
        "小颗粒": "Fine grain",
        "中颗粒": "Medium grain",
        "大颗粒": "Coarse grain",
        "暗度 35%": "Dim 35%",
        "暗度 55%": "Dim 55%",
        "暗度 70%": "Dim 70%",
        "仅描边": "Stroke",
        "仅填充": "Fill",
        "描边 + 填充": "Stroke + Fill",
        "单箭头": "Single Arrow",
        "双箭头": "Double Arrow",
        "普通": "Regular",
        "粗体": "Bold",
        "背景": "Background",
        "粗体 + 背景": "Bold + Background",
        "像素化": "Pixelate",
        "模糊": "Blur",
        "矩形高亮": "Rectangle Highlight",
        "椭圆高亮": "Ellipse Highlight",
        "单个": "Single",
        "斜向平铺": "Diagonal Tile",
        "左上": "Top Left",
        "上中": "Top Center",
        "右上": "Top Right",
        "左中": "Center Left",
        "居中": "Center",
        "右中": "Center Right",
        "左下": "Bottom Left",
        "下中": "Bottom Center",
        "右下": "Bottom Right",
        "正在准备录制文件…": "Preparing recording file...",
        "正在生成%@": "Generating %@",
        "正在准备…": "Preparing...",
        "正在编码…": "Encoding...",
        "正在完成…": "Finishing...",
        "录制完成": "Recording Complete",
        "丢弃": "Discard",
        "保存": "Save",
        "播放": "Play",
        "音量": "Volume",
        "开头": "Start",
        "结尾": "End",
        "标记删除开始": "Mark Delete Start",
        "删除至当前位置": "Delete to Playhead",
        "撤销删除片段": "Undo Deleted Segment",
        "删除片段": "Delete Segment",
        "确认删除": "Confirm Delete",
        "预览选区": "Preview Selection",
        "取消选择": "Cancel Selection",
        "恢复此片段": "Restore Segment",
        "在时间线上拖动，选择要删除的内容": "Drag on the timeline to select the content to delete",
        "将删除 %@–%@（%@）": "Delete %@–%@ (%@)",
        "已选择删除片段 %@–%@，可恢复此片段": "Deleted segment %@–%@ selected; you can restore it",
        "提取当前帧": "Extract Current Frame",
        "转为 GIF…": "Convert to GIF...",
        "选中 %@；已删除 %d 段；导出时长 %@": "Selected %@; %d segments deleted; export duration %@",
        "裁剪范围 %@；导出时长 %@": "Trim range %@; export duration %@",
        "选中 %@；删除起点 %@，请移动播放位置后点击“删除至当前位置”": "Selected %@; delete starts at %@. Move the playhead and click Delete to Playhead.",
        "请先在要删除片段的起点点击“标记删除开始”。": "Click Mark Delete Start at the beginning of the segment first.",
        "开始时间（秒）": "Start time (seconds)",
        "结束时间（秒）": "End time (seconds)",
        "最大宽度（像素）": "Maximum width (pixels)",
        "帧率（FPS）": "Frame rate (FPS)",
        "MP4 转 GIF": "MP4 to GIF",
        "选择要导出的片段、尺寸和帧率。GIF 最多 600 帧。": "Choose a segment, size, and frame rate. GIFs are limited to 600 frames.",
        "片段 %.1f 秒 · 预计 %d 帧 · %.0f FPS": "%.1f sec · about %d frames · %.0f FPS",
        "超过建议的 30 秒，GIF 可能较大且导出较慢。": "Over the recommended 30 seconds; the GIF may be large and slow to export.",
        "GIF 片段不能超过 60 秒。": "GIF segments cannot exceed 60 seconds.",
        "GIF 片段最长为 60 秒，请缩短选区。": "GIF segments are limited to 60 seconds. Shorten the selection.",
        "播放选区": "Play Selection",
        "暂停预览": "Pause Preview",
        "完整视频：点击或拖动以移动 GIF 选区": "Full video: click or drag to move the GIF selection",
        "精确选段：拖动黄色手柄，画面会同步预览": "Fine selection: drag the yellow handles to preview the matching frame",
        "GIF 不包含声音": "GIF has no audio",
        "先在完整视频中定位，再精确调整；GIF 最长 60 秒": "Locate in the full video, then fine-tune; GIFs are limited to 60 seconds",
        "选区 %@ · %.1f 秒 · 预计 %d 帧 · %.0f FPS": "Selection %@ · %.1f sec · about %d frames · %.0f FPS",
        "导出 GIF": "Export GIF",
        "GIF 时间范围无效。": "The GIF time range is invalid.",
        "正在导出…": "Exporting...",
        "剪辑后没有可导出的内容。": "There is no content left to export after editing.",
        "发现未保存的录制": "Unsaved Recording Found",
        "还有一段未保存的录制": "You Have an Unsaved Recording",
        "开始新录制前，请先保存或丢弃当前视频/GIF。": "Save or discard the current video/GIF before starting a new recording.",
        "保存并继续录制": "Save and Continue",
        "丢弃并继续录制": "Discard and Continue",
        "Brushot 找到上次未保存的录制文件。要现在恢复并打开预览吗？": "Brushot found an unsaved recording from the previous session. Recover and preview it now?",
        "恢复": "Recover",
        "稍后": "Later",
        "录制文件操作失败": "Recording File Operation Failed",
        "无法写入剪贴板。": "Unable to write to the clipboard.",
        "暂停": "Pause",
        "停止": "Stop",
        "继续": "Resume",
        "磁盘空间不足，正在安全停止…": "Low disk space. Stopping safely...",
        " · 已暂停": " · Paused",
        " · 麦克风": " · Microphone",
        " · 剩余 %@": " · %@ remaining",
        "视频": "Video",
        "视频音频": "Video Audio",
        "系统音频": "System Audio",
        "麦克风": "Microphone",
        "开始录制视频": "Start Recording Video",
        "开始录制 GIF": "Start Recording GIF",
        "GIF 最长 60 秒，建议 30 秒内 · 无声音": "GIFs: 60 seconds max, 30 seconds recommended · No audio",
        "录制格式": "Recording Format",
        "未检测到麦克风": "No microphone detected",
        "选择内置或外置麦克风": "Choose a built-in or external microphone",
        "导出时添加水印，不会出现在录制过程中": "Adds the watermark during export; it is not shown while recording",
        "请先在水印设置中填写文字或选择 Logo": "Enter text or choose a logo in Watermark Settings first",
        "导出时添加水印，不会在录制画面中显示": "Adds the watermark during export; it is not shown in the recording",
        "请先在水印设置中填写文字或选择 Logo。\n\n没有可渲染的内容时，截图水印和录制水印都无法启用。": "Enter text or choose a logo in Watermark Settings first.\n\nScreenshot and recording watermarks cannot be enabled without renderable content.",
        "截图水印会应用到截图、复制、保存、贴图等图片输出。\n\nOCR 仍读取原始图片，不受水印影响。": "Screenshot watermarks apply to captured, copied, saved, and pinned image output.\n\nOCR still reads the original image and is not affected by watermarks.",
        "水印在录制结束导出时添加，不会出现在录制过程中。\n\n开启后 MP4 需要重新编码，导出更久且画质可能轻微变化。": "Recording watermarks are added during export and do not appear while recording.\n\nWhen enabled, MP4 output may need re-encoding, which takes longer and can slightly change quality.",
        "截图水印和录制水印共享同一套文字、Logo、位置和样式。\n\n录制水印在导出时添加，MP4 可能需要更久导出。": "Screenshot and recording watermarks share the same text, logo, position, and style.\n\nRecording watermarks are added during export, so MP4 export may take longer.",
        "当前区域未识别到文字。": "No text was recognized in the selected area.",
        "翻译成中文": "Translate to Chinese",
        "复制译文": "Copy Translation",
        "OCR 文字识别": "OCR Text Recognition",
        "关闭": "Close",
        "复制原文": "Copy Original",
        "OCR 原文": "OCR Original",
        "中文译文": "Chinese Translation",
        "正在翻译…": "Translating...",
        "翻译失败": "Translation Failed",
        "无法读取长截图画面。": "Unable to read the scrolling capture image.",
        "截图区域尺寸发生变化，请重新开始长截图。": "The capture region size changed. Start the scrolling capture again.",
        "没有识别到连续内容，请减小滚动距离，并确保框选区域内没有固定栏或动画。": "No continuous content was detected. Reduce the scroll distance and make sure the selected region has no fixed bars or animations.",
        "检测到向上回滚，已自动完成长截图。": "Upward scrolling was detected, so the scrolling capture was completed automatically.",
        "长截图已达到尺寸上限，请先完成并保存当前内容。": "The scrolling capture reached the size limit. Finish and save the current content first.",
        "无法生成拼接后的长截图。": "Unable to generate the stitched scrolling capture.",
        "框内内容需全部能够上下滚动": "All content inside the box must be vertically scrollable",
        "开始长截图": "Start Scrolling Capture",
        "向下滚动采集；向上滚动立即完成，或点“完成”": "Scroll down to capture. Scroll up or click Done to finish.",
        "向上滚动立即完成": "Scroll up to finish immediately",
        "实时预览": "Live Preview",
        "标注": "Annotate",
        "长截图预览": "Scrolling Capture Preview",
        "完成标注": "Finish Annotation",
        "正在识别…": "Recognizing...",
        "长截图操作失败": "Scrolling Capture Failed",
        "再次标注…": "Annotate Again...",
        "复制图片": "Copy Image",
        "保存图片…": "Save Image...",
        "圆角": "Corner Radius",
        "直角": "Square Corners",
        "桌面行为": "Desktop Behavior",
        "固定在当前桌面": "Keep on Current Desktop",
        "跟随所有桌面": "Show on All Desktops",
        "缩放": "Zoom",
        "放大": "Zoom In",
        "缩小": "Zoom Out",
        "重置大小": "Reset Size",
        "关闭贴图": "Close Pin",
        "贴图操作失败": "Pin Operation Failed",
        "剪贴板中没有可贴出的图片。": "There is no image in the clipboard to pin.",
        "历史图片已经丢失。": "The history image is missing.",
        "Brushot 贴图库": "Brushot Pin Library",
        "贴出选中项": "Pin Selected",
        "删除记录": "Delete Record",
        "清空历史": "Clear History",
        "历史贴图": "Pin History",
        "清空贴图历史？": "Clear Pin History?",
        "已打开的贴图不会关闭，历史图片将从磁盘删除。": "Open pins will not close. History images will be deleted from disk.",
        "清空": "Clear",
        "贴图库操作失败": "Pin Library Operation Failed",
        "贴图二次标注": "Pin Annotation",
        "长截图标注": "Scrolling Capture Annotation",
        "拖动选择可滚动区域，Esc 取消": "Drag to select a scrollable region, Esc to cancel",
        "拖动选择延时截图区域，Esc 取消": "Drag to select a delayed capture region, Esc to cancel",
        "拖动选择截图区域，Esc 取消": "Drag to select a capture region, Esc to cancel",
        "正在识别文字…": "Recognizing text...",
        "正在生成图片…": "Generating image...",
        "无法读取原始截图区域。": "Unable to read the original screenshot region.",
        "未识别到文字": "No Text Recognized",
        "文字识别失败": "Text Recognition Failed",
        "需要屏幕录制权限": "Screen Recording Permission Required",
        "打开系统设置": "Open System Settings",
        "需要麦克风权限": "Microphone Permission Required",
        "截图失败": "Capture Failed",
        "macOS 未授予屏幕录制权限。": "macOS has not granted Screen Recording permission.",
        "未找到鼠标所在的显示器，无法进行全屏截图。": "Unable to find the display containing the pointer, so full screen capture cannot continue.",
        "未找到鼠标所在的显示器，无法进行全屏录屏。": "Unable to find the display containing the pointer, so full screen recording cannot continue.",
        "所选区域所在的显示器已断开，请重新截图。": "The display containing the selected region has been disconnected. Capture again.",
        "延时截图区域已失效，可能是显示器配置发生了变化。": "The delayed capture region is no longer valid. The display configuration may have changed.",
        "延时截图区域无效，请重新选择。": "The delayed capture region is invalid. Select it again.",
        "截图失败：无法通过同步冻结画面获取所选区域。请确认屏幕录制权限已开启后重试。": "Capture failed: unable to get the selected region from the frozen screen. Make sure Screen Recording permission is enabled and try again.",
        "无法进入标注：没有可用的同步冻结截图。请重新截图。": "Unable to enter annotation: no frozen screenshot is available. Capture again.",
        "无法读取同步冻结截图，已取消 OCR。请重新截图后再试。": "Unable to read the frozen screenshot, so OCR was canceled. Capture again and try later.",
        "Brushot 已向 macOS 发起屏幕录制授权申请。请在“系统设置 > 隐私与安全性 > 录屏与系统录音”中开启 Brushot，然后退出并重新打开应用。\n\n如果列表中仍没有 Brushot，请点击列表底部的“+”，手动选择“应用程序”中的 Brushot。\n\n系统信息：%@": "Brushot requested Screen Recording permission from macOS. Enable Brushot in System Settings > Privacy & Security > Screen & System Audio Recording, then quit and reopen the app.\n\nIf Brushot still is not listed, click the + button at the bottom of the list and manually choose Brushot from Applications.\n\nSystem info: %@",
        "请在“系统设置 > 隐私与安全性 > 麦克风”中允许 Brushot，然后重试。\n\n如果列表中没有 Brushot，请先确认正在运行的是新版 /Applications/Brushot.app，退出并重新打开后再录制一次；macOS 只有在应用真正请求麦克风权限后才会把它加入列表。": "Allow Brushot in System Settings > Privacy & Security > Microphone, then try again.\n\nIf Brushot is not listed, first confirm that the new /Applications/Brushot.app is running, quit and reopen it, then start recording again. macOS only adds an app to the list after it actually requests microphone permission.",
        "无法生成截图外观。": "Unable to generate screenshot appearance.",
        "等待截图画面超时。": "Timed out waiting for screenshot frames.",
        "无法确定截图所在的显示器。": "Unable to determine the display for the capture.",
        "无法读取截图所在的显示器。": "Unable to read the display for the capture.",
        "截图区域无效。": "The capture region is invalid.",
        "无法编码贴图图片。": "Unable to encode pin image.",
        "录制临时文件已经丢失。": "The temporary recording file is missing.",
        "录制文件中没有有效视频轨道。": "The recording file has no valid video track.",
        "导出失败：%@": "Export failed: %@",
        "GIF 编码失败。": "GIF encoding failed.",
        "无法创建 MP4 导出器。": "Unable to create the MP4 exporter.",
        "无法生成录制水印。": "Unable to generate the recording watermark.",
        "无法读取视频。": "Unable to read the video.",
        "GIF 读取失败。": "GIF read failed.",
        "已有录制正在进行。": "A recording is already in progress.",
        "当前没有正在进行的录制。": "There is no active recording.",
        "无法准备录制：%@": "Unable to prepare recording: %@",
        "录制写入失败：%@": "Recording write failed: %@",
        "没有录制到有效画面。": "No valid frames were recorded.",
        "没有麦克风权限。请在“系统设置 → 隐私与安全性 → 麦克风”中允许 Brushot，然后重试。": "Microphone permission is missing. Allow Brushot in System Settings > Privacy & Security > Microphone, then try again.",
        "所选麦克风不可用，请重新连接设备或选择其他麦克风。": "The selected microphone is unavailable. Reconnect it or choose another microphone.",
        "磁盘剩余空间不足 1 GB，无法安全录制。请清理空间后重试。": "Less than 1 GB of disk space remains, so recording cannot continue safely. Free up space and try again.",
        "未知错误。": "Unknown error.",
        "；底层错误：": "; underlying error: ",
        "视频编码器不可用。": "The video encoder is unavailable.",
        "%@编码器不可用。": "%@ encoder is unavailable.",
        "无法启动视频编码器。": "Unable to start the video encoder.",
        "视频编码器已停止工作。": "The video encoder stopped working.",
        "视频帧写入失败。": "Video frame write failed.",
        "%@写入失败。": "%@ write failed.",
        "Logo 图片不能超过 3MB，请选择更小的 PNG/JPG/HEIC 图片。": "Logo images cannot exceed 3 MB. Choose a smaller PNG/JPG/HEIC image.",
        "无法读取所选水印图片。": "Unable to read the selected watermark image.",
        "无法读取所选水印图片尺寸。": "Unable to read the selected watermark image dimensions.",
        "Logo 图片最长边不能超过 4096px，请先压缩后再选择。": "The longest side of the logo image cannot exceed 4096 px. Compress it before choosing it.",
        "Logo 图片比例过于细长，请选择独立图标、头像或横向短 Logo。": "The logo image is too narrow. Choose an icon, avatar, or short horizontal logo.",
        "无法生成水印 Logo 安全副本。": "Unable to create a safe copy of the watermark logo.",
        "无法保存水印 Logo 安全副本。": "Unable to save the safe copy of the watermark logo.",
        "该图片格式不适合作为水印 Logo，请选择 PNG/JPG/HEIC。": "This image format is not suitable for a watermark logo. Choose PNG/JPG/HEIC.",
        "无法生成水印图片。": "Unable to generate the watermark image.",
        "无法生成标注图片。": "Unable to generate the annotated image.",
        "无法生成马赛克效果。": "Unable to generate the mosaic effect.",
        "无法生成剪贴板图片。": "Unable to generate the clipboard image.",
        "无法写入系统剪贴板。": "Unable to write to the system clipboard.",
        "无法创建 %@ 文件。": "Unable to create the %@ file.",
        "无法将截图保存到 %@。": "Unable to save the screenshot to %@.",
        "无法生成 JPG 背景。": "Unable to generate the JPG background.",
        "白色": "White",
        "黑色": "Black",
        "红色": "Red",
        "绿色": "Green",
        "蓝色": "Blue",
        "黄色": "Yellow",
        "青色": "Cyan",
        "紫色": "Purple",
        "灰色": "Gray",
        "橙色": "Orange",
        "粉色": "Pink",
        "棕色": "Brown",
        "深红": "Dark Red",
        "深绿": "Dark Green",
        "深蓝": "Dark Blue",
        "浅蓝": "Light Blue",
        "浅绿": "Light Green",
        "浅灰": "Light Gray",
        "深灰": "Dark Gray",
        "金黄": "Gold",
        "银色": "Silver",
        "藏青": "Navy",
        "酒红": "Burgundy",
        "玫红": "Rose",
        "天蓝": "Sky Blue",
        "米色": "Beige",
        "卡其": "Khaki",
        "珊瑚": "Coral",
        "青绿": "Teal",
        "品红": "Magenta",
        "黄绿": "Yellow Green",
        "雪白": "Snow",
        "墨绿": "Dark Green",
        "胭脂": "Crimson"
    ]

    private static let japanese: [String: String] = [
        "区域截图": "範囲を撮影",
        "长截图": "スクロール撮影",
        "区域录屏": "範囲を収録",
        "全屏录屏": "画面全体を収録",
        "录屏": "収録",
        "全屏截图": "画面全体を撮影",
        "延时截图…": "タイマー撮影...",
        "从剪贴板贴图": "クリップボードからピン留め",
        "贴图库…": "ピンライブラリ...",
        "隐藏全部贴图": "すべてのピンを隠す",
        "显示全部贴图": "すべてのピンを表示",
        "贴图": "ピン",
        "退出 Brushot": "Brushot を終了",
        "编辑": "編集",
        "撤销": "取り消す",
        "重做": "やり直す",
        "剪切": "カット",
        "复制": "コピー",
        "粘贴": "ペースト",
        "全选": "すべてを選択",
        "Brushot 截图": "Brushot スクリーンショット",
        "偏好设置…": "設定...",
        "水印设置…": "ウォーターマーク設定...",
        "问题反馈…": "フィードバック...",
        "问题反馈": "フィードバック",
        "QQ交流群：1063488835\n联系邮箱：brushot@163.com": "QQ グループ: 1063488835\nメール: brushot@163.com",
        "偏好设置": "設定",
        "开机自动启动": "ログイン時に起動",
        "启用 OCR 英译中": "OCR の英中翻訳を有効化",
        "启用 OCR 英译中（需要 macOS 15 或更高版本）": "OCR の英中翻訳を有効化 (macOS 15 以降が必要)",
        "播放操作完成提示音": "完了音を再生",
        "通用": "一般",
        "语言": "言語",
        "应用语言": "アプリの言語",
        "跟随系统": "システム設定に従う",
        "重新启动 Brushot 后生效": "Brushot の再起動後に反映されます",
        "选择…": "選択...",
        "保存位置": "保存先",
        "存储格式": "形式",
        "添加阴影": "影を追加",
        "阴影大小:": "影のサイズ:",
        "颜色:": "色:",
        "增加圆角": "角丸にする",
        "默认圆角大小:": "既定の角丸:",
        "图片": "画像",
        "截图": "スクリーンショット",
        "倒计时时长": "カウントダウン時間",
        "播放倒计时提示音": "カウントダウン音を再生",
        "延时截图": "タイマー撮影",
        "快捷键": "ショートカット",
        "截图与录制": "撮影と収録",
        "输入新快捷键…": "新しいショートカットを入力...",
        "水印设置": "ウォーターマーク設定",
        "启用截图水印": "スクリーンショットのウォーターマークを有効化",
        "应用到录制视频/GIF": "収録動画/GIF に適用",
        "水印说明": "ウォーターマーク情報",
        "设置水印": "ウォーターマークを設定",
        "应用到本次截图": "このスクリーンショットに適用",
        "应用并开启录制水印": "適用して収録ウォーターマークを有効化",
        "添加文字或 Logo，应用到当前截图": "テキストまたは Logo をこのスクリーンショットに追加します",
        "添加文字或 Logo，用于导出的视频或 GIF": "書き出す動画または GIF にテキストや Logo を追加します",
        "请添加文字或 Logo；位置、透明度和大小沿用水印设置": "テキストまたは Logo を追加してください。位置、不透明度、サイズはウォーターマーク設定を使用します。",
        "文字和 Logo 至少填写一项": "テキストを入力するか Logo を選択してください。",
        "位置、透明度和大小沿用水印设置": "位置、不透明度、サイズはウォーターマーク設定を使用します。",
        "文字": "テキスト",
        "移除": "削除",
        "支持 PNG/JPG/HEIC，小于 3MB；": "3 MB 未満の PNG/JPG/HEIC に対応しています。",
        "重复方式": "繰り返し",
        "位置": "位置",
        "透明度": "不透明度",
        "大小": "サイズ",
        "边距": "余白",
        "文字颜色": "文字色",
        "水印": "ウォーターマーク",
        "水印图片无效": "ウォーターマーク画像が無効です",
        "未选择": "未選択",
        "已选择": "選択済み",
        "取消": "キャンセル",
        "开始倒计时": "カウントダウン開始",
        "%d 秒后截图": "%d 秒後に撮影",
        "%d 秒": "%d 秒",
        "选择": "選択",
        "矩形": "四角形",
        "圆形": "楕円",
        "直线": "直線",
        "箭头": "矢印",
        "画笔": "ペン",
        "步骤": "ステップ",
        "马赛克": "モザイク",
        "高亮": "ハイライト",
        "添加标注": "注釈を追加",
        "删除标注": "注釈を削除",
        "修改标注": "注釈を変更",
        "移动标注": "注釈を移動",
        "缩放标注": "注釈をリサイズ",
        "编辑文字": "テキストを編集",
        "编辑步骤文字": "ステップテキストを編集",
        "粗细": "太さ",
        "字号": "フォントサイズ",
        "笔宽": "ブラシ",
        "取消 (Esc)": "キャンセル (Esc)",
        "识别文字": "テキスト認識",
        "复制 (⌘C)": "コピー (⌘C)",
        "保存 (⌘S)": "保存 (⌘S)",
        "正在冻结截图…": "画面を固定中...",
        "完成": "完了",
        "%@，快捷键 %@": "%@、ショートカット %@",
        "选择标注颜色": "注釈の色を選択",
        "实线": "実線",
        "虚线": "破線",
        "点线": "点線",
        "仅描边": "線のみ",
        "仅填充": "塗りのみ",
        "描边 + 填充": "線 + 塗り",
        "单箭头": "片矢印",
        "双箭头": "両矢印",
        "普通": "標準",
        "粗体": "太字",
        "背景": "背景",
        "粗体 + 背景": "太字 + 背景",
        "像素化": "ピクセル化",
        "模糊": "ぼかし",
        "单个": "単体",
        "斜向平铺": "斜めに並べる",
        "左上": "左上",
        "上中": "上中央",
        "右上": "右上",
        "左中": "左中央",
        "居中": "中央",
        "右中": "右中央",
        "左下": "左下",
        "下中": "下中央",
        "右下": "右下",
        "正在准备录制文件…": "収録ファイルを準備中...",
        "正在生成%@": "%@ を生成中",
        "正在准备…": "準備中...",
        "正在编码…": "エンコード中...",
        "正在完成…": "仕上げ中...",
        "录制完成": "収録完了",
        "丢弃": "破棄",
        "保存": "保存",
        "播放": "再生",
        "音量": "音量",
        "开头": "開始",
        "结尾": "終了",
        "标记删除开始": "削除開始をマーク",
        "删除至当前位置": "現在位置まで削除",
        "撤销删除片段": "削除区間を元に戻す",
        "删除片段": "区間を削除",
        "确认删除": "削除を確定",
        "预览选区": "選択範囲をプレビュー",
        "取消选择": "選択をキャンセル",
        "恢复此片段": "この区間を復元",
        "在时间线上拖动，选择要删除的内容": "タイムライン上をドラッグして削除する範囲を選択してください",
        "将删除 %@–%@（%@）": "%@–%@（%@）を削除",
        "已选择删除片段 %@–%@，可恢复此片段": "削除済み区間 %@–%@ を選択中。復元できます",
        "提取当前帧": "現在のフレームを保存",
        "转为 GIF…": "GIF に変換…",
        "选中 %@；已删除 %d 段；导出时长 %@": "選択 %@・%d 区間削除・書き出し時間 %@",
        "裁剪范围 %@；导出时长 %@": "トリミング範囲 %@・書き出し時間 %@",
        "选中 %@；删除起点 %@，请移动播放位置后点击“删除至当前位置”": "選択 %@・削除開始 %@。再生位置を移動して「現在位置まで削除」をクリックしてください。",
        "请先在要删除片段的起点点击“标记删除开始”。": "削除する区間の先頭で「削除開始をマーク」をクリックしてください。",
        "开始时间（秒）": "開始時間（秒）",
        "结束时间（秒）": "終了時間（秒）",
        "最大宽度（像素）": "最大幅（ピクセル）",
        "帧率（FPS）": "フレームレート（FPS）",
        "MP4 转 GIF": "MP4 を GIF に変換",
        "选择要导出的片段、尺寸和帧率。GIF 最多 600 帧。": "書き出す区間、サイズ、フレームレートを選択します。GIF は最大 600 フレームです。",
        "片段 %.1f 秒 · 预计 %d 帧 · %.0f FPS": "%.1f 秒・約 %d フレーム・%.0f FPS",
        "超过建议的 30 秒，GIF 可能较大且导出较慢。": "推奨の 30 秒を超えています。GIF が大きくなり、書き出しに時間がかかる場合があります。",
        "GIF 片段不能超过 60 秒。": "GIF の区間は 60 秒を超えられません。",
        "GIF 片段最长为 60 秒，请缩短选区。": "GIF の区間は最大 60 秒です。選択範囲を短くしてください。",
        "播放选区": "選択範囲を再生",
        "暂停预览": "プレビューを一時停止",
        "完整视频：点击或拖动以移动 GIF 选区": "動画全体：クリックまたはドラッグで GIF 範囲を移動",
        "精确选段：拖动黄色手柄，画面会同步预览": "詳細選択：黄色のハンドルをドラッグすると映像も同期します",
        "GIF 不包含声音": "GIF に音声は含まれません",
        "先在完整视频中定位，再精确调整；GIF 最长 60 秒": "動画全体で位置を決めてから微調整します。GIF は最大 60 秒です",
        "选区 %@ · %.1f 秒 · 预计 %d 帧 · %.0f FPS": "範囲 %@・%.1f 秒・約 %d フレーム・%.0f FPS",
        "导出 GIF": "GIF を書き出す",
        "GIF 时间范围无效。": "GIF の時間範囲が無効です。",
        "正在导出…": "書き出し中…",
        "剪辑后没有可导出的内容。": "編集後に書き出せる内容がありません。",
        "发现未保存的录制": "未保存の収録が見つかりました",
        "还有一段未保存的录制": "未保存の収録があります",
        "开始新录制前，请先保存或丢弃当前视频/GIF。": "新しい収録を始める前に、現在の動画/GIF を保存または破棄してください。",
        "保存并继续录制": "保存して続ける",
        "丢弃并继续录制": "破棄して続ける",
        "Brushot 找到上次未保存的录制文件。要现在恢复并打开预览吗？": "前回保存されなかった収録が見つかりました。復元してプレビューしますか？",
        "恢复": "復元",
        "稍后": "後で",
        "暂停": "一時停止",
        "停止": "停止",
        "继续": "再開",
        "视频": "動画",
        "视频音频": "動画音声",
        "系统音频": "システム音声",
        "麦克风": "マイク",
        "开始录制视频": "動画収録を開始",
        "开始录制 GIF": "GIF 収録を開始",
        "GIF 最长 60 秒，建议 30 秒内 · 无声音": "GIF は最大 60 秒、30 秒以内を推奨 · 音声なし",
        "录制格式": "収録形式",
        "未检测到麦克风": "マイクが検出されません",
        "翻译成中文": "中国語に翻訳",
        "复制译文": "翻訳をコピー",
        "OCR 文字识别": "OCR テキスト認識",
        "关闭": "閉じる",
        "复制原文": "原文をコピー",
        "OCR 原文": "OCR 原文",
        "中文译文": "中国語訳",
        "正在翻译…": "翻訳中...",
        "翻译失败": "翻訳に失敗しました",
        "框内内容需全部能够上下滚动": "枠内の内容全体が上下にスクロール可能である必要があります",
        "开始长截图": "スクロール撮影を開始",
        "实时预览": "ライブプレビュー",
        "标注": "注釈",
        "长截图预览": "スクロール撮影プレビュー",
        "完成标注": "注釈を完了",
        "正在识别…": "認識中...",
        "再次标注…": "再注釈...",
        "复制图片": "画像をコピー",
        "保存图片…": "画像を保存...",
        "圆角": "角丸",
        "直角": "角丸なし",
        "桌面行为": "デスクトップ動作",
        "固定在当前桌面": "現在のデスクトップに固定",
        "跟随所有桌面": "すべてのデスクトップに表示",
        "缩放": "ズーム",
        "放大": "拡大",
        "缩小": "縮小",
        "重置大小": "サイズをリセット",
        "关闭贴图": "ピンを閉じる",
        "Brushot 贴图库": "Brushot ピンライブラリ",
        "贴出选中项": "選択項目をピン留め",
        "删除记录": "履歴を削除",
        "清空历史": "履歴を消去",
        "历史贴图": "ピン履歴",
        "清空": "消去",
        "拖动选择可滚动区域，Esc 取消": "ドラッグしてスクロール領域を選択、Esc でキャンセル",
        "拖动选择延时截图区域，Esc 取消": "ドラッグしてタイマー撮影領域を選択、Esc でキャンセル",
        "拖动选择截图区域，Esc 取消": "ドラッグして撮影領域を選択、Esc でキャンセル",
        "正在识别文字…": "テキストを認識中...",
        "正在生成图片…": "画像を生成中...",
        "未识别到文字": "テキストが認識されません",
        "文字识别失败": "テキスト認識に失敗しました",
        "需要屏幕录制权限": "画面収録の権限が必要です",
        "打开系统设置": "システム設定を開く",
        "需要麦克风权限": "マイクの権限が必要です",
        "截图失败": "撮影に失敗しました",
        "未知错误。": "不明なエラーです。",
        "白色": "白",
        "黑色": "黒",
        "红色": "赤",
        "绿色": "緑",
        "蓝色": "青",
        "黄色": "黄",
        "灰色": "グレー",
        "橙色": "オレンジ"
    ]

    private static let korean: [String: String] = [
        "区域截图": "영역 캡처",
        "长截图": "스크롤 캡처",
        "区域录屏": "영역 녹화",
        "全屏录屏": "전체 화면 녹화",
        "录屏": "녹화",
        "全屏截图": "전체 화면 캡처",
        "延时截图…": "타이머 캡처...",
        "从剪贴板贴图": "클립보드에서 핀 고정",
        "贴图库…": "핀 라이브러리...",
        "隐藏全部贴图": "모든 핀 숨기기",
        "显示全部贴图": "모든 핀 보이기",
        "贴图": "핀",
        "退出 Brushot": "Brushot 종료",
        "编辑": "편집",
        "撤销": "실행 취소",
        "重做": "다시 실행",
        "剪切": "잘라내기",
        "复制": "복사",
        "粘贴": "붙여넣기",
        "全选": "전체 선택",
        "Brushot 截图": "Brushot 스크린샷",
        "偏好设置…": "설정...",
        "水印设置…": "워터마크 설정...",
        "问题反馈…": "피드백...",
        "问题反馈": "피드백",
        "QQ交流群：1063488835\n联系邮箱：brushot@163.com": "QQ 그룹: 1063488835\n이메일: brushot@163.com",
        "偏好设置": "설정",
        "开机自动启动": "로그인 시 실행",
        "启用 OCR 英译中": "OCR 영어-중국어 번역 사용",
        "启用 OCR 英译中（需要 macOS 15 或更高版本）": "OCR 영어-중국어 번역 사용(macOS 15 이상 필요)",
        "播放操作完成提示音": "완료 알림음 재생",
        "通用": "일반",
        "语言": "언어",
        "应用语言": "앱 언어",
        "跟随系统": "시스템 설정 따르기",
        "重新启动 Brushot 后生效": "Brushot을 다시 시작하면 적용됩니다",
        "选择…": "선택...",
        "保存位置": "저장 위치",
        "存储格式": "형식",
        "添加阴影": "그림자 추가",
        "阴影大小:": "그림자 크기:",
        "颜色:": "색상:",
        "增加圆角": "둥근 모서리",
        "默认圆角大小:": "기본 모서리 반경:",
        "图片": "이미지",
        "截图": "스크린샷",
        "倒计时时长": "카운트다운 시간",
        "播放倒计时提示音": "카운트다운 소리 재생",
        "延时截图": "타이머 캡처",
        "快捷键": "단축키",
        "截图与录制": "캡처 및 녹화",
        "输入新快捷键…": "새 단축키 입력...",
        "水印设置": "워터마크 설정",
        "启用截图水印": "스크린샷 워터마크 사용",
        "应用到录制视频/GIF": "녹화 영상/GIF에 적용",
        "水印说明": "워터마크 정보",
        "设置水印": "워터마크 설정",
        "应用到本次截图": "이 스크린샷에 적용",
        "应用并开启录制水印": "적용하고 녹화 워터마크 켜기",
        "添加文字或 Logo，应用到当前截图": "이 스크린샷에 텍스트 또는 Logo를 추가합니다",
        "添加文字或 Logo，用于导出的视频或 GIF": "내보낼 동영상 또는 GIF에 텍스트나 Logo를 추가합니다",
        "请添加文字或 Logo；位置、透明度和大小沿用水印设置": "텍스트 또는 Logo를 추가하세요. 위치, 불투명도 및 크기는 워터마크 설정을 사용합니다.",
        "文字和 Logo 至少填写一项": "텍스트를 입력하거나 Logo를 선택하세요.",
        "位置、透明度和大小沿用水印设置": "위치, 불투명도 및 크기는 워터마크 설정을 사용합니다.",
        "文字": "텍스트",
        "移除": "제거",
        "支持 PNG/JPG/HEIC，小于 3MB；": "3MB 미만의 PNG/JPG/HEIC를 지원합니다.",
        "重复方式": "반복",
        "位置": "위치",
        "透明度": "불투명도",
        "大小": "크기",
        "边距": "여백",
        "文字颜色": "텍스트 색상",
        "水印": "워터마크",
        "水印图片无效": "잘못된 워터마크 이미지",
        "未选择": "선택 안 함",
        "已选择": "선택됨",
        "取消": "취소",
        "开始倒计时": "카운트다운 시작",
        "%d 秒后截图": "%d초 후 캡처",
        "%d 秒": "%d초",
        "选择": "선택",
        "矩形": "사각형",
        "圆形": "타원",
        "直线": "직선",
        "箭头": "화살표",
        "画笔": "펜",
        "步骤": "단계",
        "马赛克": "모자이크",
        "高亮": "하이라이트",
        "添加标注": "주석 추가",
        "删除标注": "주석 삭제",
        "修改标注": "주석 수정",
        "移动标注": "주석 이동",
        "缩放标注": "주석 크기 조절",
        "编辑文字": "텍스트 편집",
        "编辑步骤文字": "단계 텍스트 편집",
        "粗细": "두께",
        "字号": "글꼴 크기",
        "笔宽": "브러시",
        "取消 (Esc)": "취소(Esc)",
        "识别文字": "텍스트 인식",
        "复制 (⌘C)": "복사(⌘C)",
        "保存 (⌘S)": "저장(⌘S)",
        "正在冻结截图…": "화면을 고정하는 중...",
        "完成": "완료",
        "%@，快捷键 %@": "%@, 단축키 %@",
        "选择标注颜色": "주석 색상 선택",
        "实线": "실선",
        "虚线": "파선",
        "点线": "점선",
        "仅描边": "선만",
        "仅填充": "채우기만",
        "描边 + 填充": "선 + 채우기",
        "单箭头": "단일 화살표",
        "双箭头": "양방향 화살표",
        "普通": "일반",
        "粗体": "굵게",
        "背景": "배경",
        "粗体 + 背景": "굵게 + 배경",
        "像素化": "픽셀화",
        "模糊": "흐림",
        "单个": "단일",
        "斜向平铺": "대각선 타일",
        "左上": "왼쪽 위",
        "上中": "위 가운데",
        "右上": "오른쪽 위",
        "左中": "왼쪽 가운데",
        "居中": "가운데",
        "右中": "오른쪽 가운데",
        "左下": "왼쪽 아래",
        "下中": "아래 가운데",
        "右下": "오른쪽 아래",
        "正在准备录制文件…": "녹화 파일 준비 중...",
        "正在生成%@": "%@ 생성 중",
        "正在准备…": "준비 중...",
        "正在编码…": "인코딩 중...",
        "正在完成…": "마무리 중...",
        "录制完成": "녹화 완료",
        "丢弃": "버리기",
        "保存": "저장",
        "播放": "재생",
        "音量": "음량",
        "开头": "시작",
        "结尾": "끝",
        "标记删除开始": "삭제 시작 표시",
        "删除至当前位置": "현재 위치까지 삭제",
        "撤销删除片段": "삭제 구간 실행 취소",
        "删除片段": "구간 삭제",
        "确认删除": "삭제 확인",
        "预览选区": "선택 영역 미리보기",
        "取消选择": "선택 취소",
        "恢复此片段": "이 구간 복원",
        "在时间线上拖动，选择要删除的内容": "타임라인에서 드래그하여 삭제할 내용을 선택하세요",
        "将删除 %@–%@（%@）": "%@–%@(%@) 삭제",
        "已选择删除片段 %@–%@，可恢复此片段": "삭제된 구간 %@–%@ 선택됨. 이 구간을 복원할 수 있습니다",
        "提取当前帧": "현재 프레임 추출",
        "转为 GIF…": "GIF로 변환…",
        "选中 %@；已删除 %d 段；导出时长 %@": "선택 %@ · %d개 구간 삭제 · 내보내기 길이 %@",
        "裁剪范围 %@；导出时长 %@": "트리밍 범위 %@ · 내보내기 길이 %@",
        "选中 %@；删除起点 %@，请移动播放位置后点击“删除至当前位置”": "선택 %@ · 삭제 시작 %@. 재생 위치를 옮긴 후 ‘현재 위치까지 삭제’를 클릭하세요.",
        "请先在要删除片段的起点点击“标记删除开始”。": "삭제할 구간의 시작에서 ‘삭제 시작 표시’를 먼저 클릭하세요.",
        "开始时间（秒）": "시작 시간(초)",
        "结束时间（秒）": "종료 시간(초)",
        "最大宽度（像素）": "최대 너비(픽셀)",
        "帧率（FPS）": "프레임 속도(FPS)",
        "MP4 转 GIF": "MP4를 GIF로 변환",
        "选择要导出的片段、尺寸和帧率。GIF 最多 600 帧。": "내보낼 구간, 크기 및 프레임 속도를 선택하세요. GIF는 최대 600프레임입니다.",
        "片段 %.1f 秒 · 预计 %d 帧 · %.0f FPS": "%.1f초 · 약 %d프레임 · %.0f FPS",
        "超过建议的 30 秒，GIF 可能较大且导出较慢。": "권장 30초를 초과했습니다. GIF가 커지고 내보내기가 느릴 수 있습니다.",
        "GIF 片段不能超过 60 秒。": "GIF 구간은 60초를 초과할 수 없습니다.",
        "GIF 片段最长为 60 秒，请缩短选区。": "GIF 구간은 최대 60초입니다. 선택 범위를 줄이세요.",
        "播放选区": "선택 구간 재생",
        "暂停预览": "미리보기 일시 정지",
        "完整视频：点击或拖动以移动 GIF 选区": "전체 동영상: 클릭하거나 드래그해 GIF 구간 이동",
        "精确选段：拖动黄色手柄，画面会同步预览": "세부 선택: 노란색 핸들을 드래그하면 영상이 동기화됩니다",
        "GIF 不包含声音": "GIF에는 소리가 포함되지 않습니다",
        "先在完整视频中定位，再精确调整；GIF 最长 60 秒": "전체 동영상에서 위치를 정한 뒤 세부 조정하세요. GIF는 최대 60초입니다",
        "选区 %@ · %.1f 秒 · 预计 %d 帧 · %.0f FPS": "선택 %@ · %.1f초 · 약 %d프레임 · %.0f FPS",
        "导出 GIF": "GIF 내보내기",
        "GIF 时间范围无效。": "GIF 시간 범위가 올바르지 않습니다.",
        "正在导出…": "내보내는 중…",
        "剪辑后没有可导出的内容。": "편집 후 내보낼 내용이 없습니다.",
        "发现未保存的录制": "저장되지 않은 녹화 발견",
        "还有一段未保存的录制": "저장하지 않은 녹화가 있습니다",
        "开始新录制前，请先保存或丢弃当前视频/GIF。": "새 녹화를 시작하기 전에 현재 동영상/GIF를 저장하거나 버리세요.",
        "保存并继续录制": "저장하고 계속 녹화",
        "丢弃并继续录制": "버리고 계속 녹화",
        "Brushot 找到上次未保存的录制文件。要现在恢复并打开预览吗？": "이전 세션에서 저장되지 않은 녹화를 찾았습니다. 지금 복구하여 미리 보시겠습니까?",
        "恢复": "복구",
        "稍后": "나중에",
        "暂停": "일시 정지",
        "停止": "정지",
        "继续": "계속",
        "视频": "동영상",
        "视频音频": "동영상 오디오",
        "系统音频": "시스템 오디오",
        "麦克风": "마이크",
        "开始录制视频": "동영상 녹화 시작",
        "开始录制 GIF": "GIF 녹화 시작",
        "GIF 最长 60 秒，建议 30 秒内 · 无声音": "GIF는 최대 60초, 30초 이내 권장 · 소리 없음",
        "录制格式": "녹화 형식",
        "未检测到麦克风": "마이크가 감지되지 않음",
        "翻译成中文": "중국어로 번역",
        "复制译文": "번역 복사",
        "OCR 文字识别": "OCR 텍스트 인식",
        "关闭": "닫기",
        "复制原文": "원문 복사",
        "OCR 原文": "OCR 원문",
        "中文译文": "중국어 번역",
        "正在翻译…": "번역 중...",
        "翻译失败": "번역 실패",
        "框内内容需全部能够上下滚动": "상자 안의 모든 내용이 세로로 스크롤 가능해야 합니다",
        "开始长截图": "스크롤 캡처 시작",
        "实时预览": "실시간 미리보기",
        "标注": "주석",
        "长截图预览": "스크롤 캡처 미리보기",
        "完成标注": "주석 완료",
        "正在识别…": "인식 중...",
        "再次标注…": "다시 주석...",
        "复制图片": "이미지 복사",
        "保存图片…": "이미지 저장...",
        "圆角": "둥근 모서리",
        "直角": "각진 모서리",
        "桌面行为": "데스크톱 동작",
        "固定在当前桌面": "현재 데스크톱에 고정",
        "跟随所有桌面": "모든 데스크톱에 표시",
        "缩放": "확대/축소",
        "放大": "확대",
        "缩小": "축소",
        "重置大小": "크기 재설정",
        "关闭贴图": "핀 닫기",
        "Brushot 贴图库": "Brushot 핀 라이브러리",
        "贴出选中项": "선택 항목 핀 고정",
        "删除记录": "기록 삭제",
        "清空历史": "기록 지우기",
        "历史贴图": "핀 기록",
        "清空": "지우기",
        "拖动选择可滚动区域，Esc 取消": "드래그하여 스크롤 영역 선택, Esc로 취소",
        "拖动选择延时截图区域，Esc 取消": "드래그하여 타이머 캡처 영역 선택, Esc로 취소",
        "拖动选择截图区域，Esc 取消": "드래그하여 캡처 영역 선택, Esc로 취소",
        "正在识别文字…": "텍스트 인식 중...",
        "正在生成图片…": "이미지 생성 중...",
        "未识别到文字": "인식된 텍스트 없음",
        "文字识别失败": "텍스트 인식 실패",
        "需要屏幕录制权限": "화면 녹화 권한 필요",
        "打开系统设置": "시스템 설정 열기",
        "需要麦克风权限": "마이크 권한 필요",
        "截图失败": "캡처 실패",
        "未知错误。": "알 수 없는 오류입니다.",
        "白色": "흰색",
        "黑色": "검은색",
        "红色": "빨간색",
        "绿色": "초록색",
        "蓝色": "파란색",
        "黄色": "노란색",
        "灰色": "회색",
        "橙色": "주황색"
    ]

    static let languagePreferenceAtLaunch = AppLanguagePreferences.selectedLanguage()

    private static let activeLanguage: Language = resolvedLanguage(for: languagePreferenceAtLaunch)

    private static func resolvedLanguage(for preference: AppLanguage) -> Language {
        switch preference {
        case .simplifiedChinese:
            return .simplifiedChinese
        case .traditionalChinese:
            return .traditionalChinese
        case .english:
            return .english
        case .japanese:
            return .japanese
        case .korean:
            return .korean
        case .system:
            break
        }

        for rawLanguage in Locale.preferredLanguages {
            let language = rawLanguage.lowercased()
            if language.hasPrefix("zh-hant")
                || language.contains("-hant")
                || language.hasPrefix("zh-tw")
                || language.hasPrefix("zh-hk")
                || language.hasPrefix("zh-mo") {
                return .traditionalChinese
            }
            if language.hasPrefix("zh") {
                return .simplifiedChinese
            }
            if language.hasPrefix("ja") {
                return .japanese
            }
            if language.hasPrefix("ko") {
                return .korean
            }
            if language.hasPrefix("en") {
                return .english
            }
        }
        return .english
    }

    static var isChinesePreferred: Bool {
        switch activeLanguage {
        case .simplifiedChinese, .traditionalChinese:
            true
        case .japanese, .korean, .english:
            false
        }
    }

    static func text(_ key: String) -> String {
        switch activeLanguage {
        case .simplifiedChinese:
            key
        case .traditionalChinese:
            traditionalChineseText(for: key)
        case .japanese:
            japanese[key] ?? english[key] ?? key
        case .korean:
            korean[key] ?? english[key] ?? key
        case .english:
            english[key] ?? key
        }
    }

    static func format(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: text(key), locale: Locale.current, arguments: arguments)
    }

    private static func traditionalChineseText(for key: String) -> String {
        let mutable = NSMutableString(string: key)
        CFStringTransform(
            mutable,
            nil,
            "Hans-Hant" as CFString,
            false
        )
        return mutable as String
    }
}

extension String {
    var localized: String { L.text(self) }
}
